apiVersion: v1
kind: Secret
metadata:
  name: ashish-github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/hello2ashu/My-repo
  password: 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
#  username: hello2ashu
