apiVersion: v1
kind: Secret
metadata:
  name: ashish-github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/hello2ashu/argocd-training 
  password: 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 
#  username: hello2ashu
